### ISSUE TITLE
noun not nouning

### ISSUE THREAD

**Issue by Spit-fires** [ProjectTEST-AI/Webpage#2]
![image](https://github.com/ProjectTEST-AI/Webpage/assets/84981998/af4fd493-dcef-4dd8-bebb-ab0cd62dfec9)

the noun here is not capitalizatized.
this has caused me emotional damage.

**Comment by Yarplay1** [comment]
Lemme fix it

**Comment by Spit-fires** [comment]
now i dont have emotional damage

**Comment by JasonP01** [comment]
sound like you still have emotional skill issue tho
